function initStrings(rand, { moon, sun, rising }) {
  function pickRandom(xs) {
    return xs[Math.floor(rand() * xs.length)]
  }

  const rules = {
    random: () => pickRandom([ "hello", "bye" ]),
    moon: () => moon,
    sun: () => sun,
    rising: () => rising,
    sign: () => pickRandom([ "#moon moon", "#sun sun", "#rising rising" ]),
    signs: () => pickRandom([ "#moon moons", "#sun suns", "#rising risings" ]),
    mainSentence: () => "#flavour#finalSentence",

    clashmoon: () => pickRandom([
      "Something's not right. You're prone to emotional outbursts.",
      "It's hard to explain exactly why you're upset.",
      "Something looms underneath the surface. You might struggle to keep it contained.",
      "You feel like letting out a deep sigh."
    ]),
    weakmoon: () => pickRandom([
      "Things carry on as usual.",
      "If your therapist called, there's a 50/50 chance you'd pick up.",
      "You feel like reading a good book.",
      "The stars have nothing in store for you. The day is all yours.",
      "You feel more or less safe. Somewhere, at the back of your mind, stress grows like a housefire."
    ]),
    synergymoon: () => pickRandom([
      "You have everything it takes to redefine your emotional life.",
      "You have mental fortitude. You could sleep on the floor without accruing any back pain.",
      "This evening, you'll watch a Netflix series without feeling any guilt about it."
    ]),

    clashsun: () => pickRandom([
      "Your shoes are likely to come undone on your daily walk.",
      "There's a moderate-to-large risk you fall down the stairs soon.",
      "Everything is in disarray. You're not sure where you left your keys."
    ]),
    weaksun: () => pickRandom([
      "The day is completely in your hands.",
      "Sometimes important conversations start off awkward, but end up wonderful and energising.",
      "Today is just another day."
    ]),
    synergysun: () => pickRandom([
      "Today, everything on your to-do list runs smoothly.",
      "You're dressed perfectly for today's weather forecast.",
      "You know yourself well. Important decisions come easy to you."
    ]),

    clashrising: () => pickRandom([
      "There's a mob waiting to lynch you outside your door.",
      "If you tried, you would utterly mess up any piece of public speaking.",
      "The ants underneath your floorboards struggle to understand you."
    ]),
    weakrising: () => pickRandom([
      "People aren't always sure what to make of you.",
      "Some of your teachers remember you fondly. Most have forgotten you.",
      "Your near-future interactions with customer service will be mildly pleasant."
    ]),
    synergyrising: () => pickRandom([
      "In this light, even your worst qualities look like the traits of a superhero.",
      "You impress any and all guests you have over for dinner.",
      "Dozens of people find you funny."
    ]),

    flavour: () => pickRandom([
      "As a #sign, shying away from conflict has never come easy. Today, #today",
      "As a #sign, you can always tell what's best for you. #encouragement",
      "As a #sign, you should remember to stand up for yourself. #encouragement",
      "As a #sign, it can be hard to tell where to draw the line. Today, #today",
      "Someone out there wants to be your record player, baby, if you know what I mean. Today, #today",
      "Sometimes things take longer than you'd like to manifest. Today, #today",
      "Today, #today",
      "Real freedom can only come about putting yourself firmly in the hands of the people you love. Today, #today",
      "It's okay to linger in bed for longer than you'd like. Everything waits for you. #encouragement",
      "You're unstoppable. The world itself has always prayed for your success. Today, #today",
      "The water pressure in your shower is near impossible to beat. #encouragement",
      "The mist in Innsbruck is rising. A whole new universe is about to unsheathe itself.",
      "The robot uprising has got nothing on you. #encouragement",
      "You don't need ChatGPT to excel. #encouragement",
      "The seagulls are the ones who should be afraid of *you*. #encouragement",
      "You should invite someone new out for coffee. People are ready for connection if you are.",
      "You should invite someone new out for coffee. They've got incredible gossip to tell you.",
      "Things will become clear sooner than you think. Today, #today",
      "Things will become clear sooner than you think. #encouragement",
      "Today, you should stick to tradition. Revive a near-forgotten inside joke.",
      "Today, you should stick to tradition. Sit in your favourite spot in the library.",
      "Conservatism never suited you. Today, something needs to change. #trySomethingNew",
      "It's never too late to change something drastic. #trySomethingNew",
      "Your cousin's marriage is still going strong. #encouragement",
      "You get to choose what you inherit from your parents. Today, #today",
      "A sufficiently delayed train puts money in your pocket. Today, #today",
      "A sufficiently delayed train puts money in your pocket. #encouragement",
      "There is no wisdom to offer you that you don't already know yourself. That said, #today",
      "It's impossible to tell you something you couldn't figure out on your own. Still, #today",
      "With trial and error, you could learn how to make amazing salads. Today, #today",
      "Today, #today", "Today, #today", "Today, #today", "Tomorrow, #today",
      "All things considered, today wasn't all that important, after all.",
      "As a #sign, important meetings always go your way. #encouragement",
      "As a #sign, it's easy to miss the forest for the trees. Today, #today",
      "As a #sign, sometimes you need help expressing your feelings without rationalising them. Today, #today",
      "There is always a risk to be taken. #trySomethingNew",
      "#calm.",
      "The world isn't always predictable. #calm.",
      "It's important to find something to call home, no matter your journey through life. #calm.",
      "No matter its allure, a visit to Denmark never ends well. #calm instead.",
      "The rest of your day will be quite easy. You'll do all the jobs on your list, and enjoy them, and have some time over. You are full of love. You're glad you exist.",
      "Someone you know is eager for you to reach out to them. Today, #today",
      "Your favourite song won't always impact you the way it did at first. Today, #today",
      "Whoever you are, no matter how lonely, the world offers itself to your imagination. #calm.",
      "Whoever you are, no matter how lonely, the world offers itself to your imagination. #encouragement",
      "He stands his ground. The planet goes on being round. #encouragement",
      "So if you don't know, don't give up. Maybe tomorrow you'll know. #encouragement",
      "As a #sign, you're weirdly good at flirting. Today, #today",
      "As a #sign, you know what it's like to surprise people. Today, #today",
      "You've known for a while now that this day would come. #encouragement",
      "It's true: you're a big fan of lemons. Today, #today",
      "There are films out there practically begging you to watch them. Today, #today",
      "Have you consumed any long-form content today? #encouragement",
      "As a #sign, you tend to remember to water your plants. #encouragement",
      "As a #sign, there really isn't much to say about you. Today, #today",
      "You're not like other #signs. Use it to your advantage.",
      "You're not like other #signs. #encouragement",
      "You look stunning today. #encouragement",
      "You look stunning today. #calm.",
      "You look beautiful today. #trySomethingNew",
      "You're not sure if that guy was hitting on you or not. Today, #today",
      "You're not sure if that guy was hitting on you or not. But he should've been. #encouragement",
      "Committees are hard work. Today, #today",
      "Committees are hard work. #encouragement",
      "Insert quote from your favourite song. Today, #today",
      "Insert quote from your favourite book. Today, #today",
      "You shouldn't always be the one who has to organise things. Today, #today",
      "Maths maths maths code code code. #encouragement",
      "Your blog posts provide so much business value. Today, #today",
      "Your favourite book might just be set in Sweden. Today, #today",
      "Soon, the sap will begin rising from the roots. #encouragement",
      "You cannot teach your father the ways of gentleness if he is not ready to listen. Today, #today",
      "Your blood is a circuit the exact shape of your body. #encouragement",
      "A planet is a body. #trySomethingNew"
    ]),
    today: () => pickRandom([
      "commit hard to a bit, and don't let anyone deter you.",
      "your best bet is possibly staying in bed, spooning your toy turtle.",
      "it's okay to fantasise about DevOps solutions for Salesforce. We've all been there.",
      "fish stay away from the lens of your camera moreso than ever before.",
      "an argument will break out regarding the thermostat. Pick sides carefully.",
      "your email inbox is finally going to overflow. Invite the mess into your life: let it free you.",
      "you won't get the Wordle in two. Your luck is better spent where it counts.",
      "the NYT Connections will be a struggle. Remember: asking your boyfriend for help is always acceptable.",
      "all the stars align. You'll solve the NYT Connections with zero mistakes, in perfect sequence, from yellow to purple.",
      "someone somewhere is thinking of buying you a tomato-themed cookbook.",
      "the fish want to be your friend. Offer a kind word; help keep the sharks at bay.",
      "mould grows in the corner of your room, behind your bed. Pick up your gloves and get to work.",
      "your boyfriend wants to make you a sandwich. Make sure he's living up to his potential.",
      "your inner world is beset by more winds than usual. You should pack that coat that makes you look like a baby.",
      "browsing TikTok will only worsen your baby fever.",
      "browsing TikTok will stoke the flames of your rage against the male gender.",
      "you're feeling adventurous. Maybe it's time to go for a cold-water swim.",
      "you really don't have to pick up the phone when your mum rings.",
      "you're seventeen again. You're not scared of death: you have dreams again.",
      "she x on my y 'til I z.",
      "point out your favourite cloud in the sky.",
      "you deserve several portions of your favourite breakfast.",
      "you deserve an evening walk to get ice cream.",
      "the emails won't write themselves.",
      "you should learn to lean back on the people you trust.",
      "talk about your Salesforce DevOps internship the way a rich girl would describe her year abroad in Spain.",
      "you'll probably say you're cold at one point or another, statistically speaking.",
      "you should call someone an ugly bitch.",
      "don't shy away from telling people to piss off.",
      "have a difficult conversation. Air your concerns.",
      "your flatmate can't wait to share some important news.",
      "make a new memory. #trySomethingNew",
      "you're starting to get bored. #trySomethingNew",
      "everything is in its right place. #calm.",
      "there is nothing that needs your attention. #calm.",
      "reach out to the #superlativePerson you know.",
      "remember to value honesty.",
      "try revisiting your favourite poem.",
      "your boyfriend should pay for you to get your nails done.",
      "you do not have to be good. You do not have to walk on your knees for a hundred miles through the desert repenting.",
      "you only have to let the soft animal of your body love what it loves.",
      "no buttons need sewing back on to coats. Take the day to yourself.",
      "you know your love should be celebrated.",
      "think deeply about your dream life.",
      "don't ponder for too long the dreams you had last night.",
      "you will guess the flavour of tea on your first attempt.",
      "watch the women's football.",
      "remember your #sign identity.",
      "organise an Indian wedding.",
      "forget about folding your laundry.",
      "slippers will bring you comfort.",
      "your favourite hot chocolate calls to you.",
      "you'll be left on read, metaphorically speaking.",
      "Swedish engineers are clawing down your door.",
      "have a tea break.",
      "don't offer to pay for the bill."
    ]),
    encouragement: () => pickRandom([
      "Whatever you're scared of, deep down, you know you're more than capable of pulling it off.",
      "One of your friends recently described you as the #superlativePerson they know.",
      "A stranger thinks you might be the #superlativePerson ever.",
      "Someone you love is thinking about you. Open yourself up to the idea of peace.",
      "If you went to the gym lately, you surely did great.",
      "The person you were at fifteen would be proud to see you today.",
      "You have what it takes to set a Monday crossword world record.",
      "No one cleans a bathroom the way you do.",
      "If we're being totally fair, you've probably never once lost an argument.",
      "Your vocabulary in Tamil is more advanced than you believe.",
      "It's not called being cheap, it's called having basic budgeting skills.",
      "#encouragement Don't let anyone tell you otherwise.",
      "#encouragement And that's that.",
      "You're breaking the cycles of intergenerational trauma.",
      "You would be prime minister by now, if it weren't for that sore spot on your back.",
      "Your diss supervisor would write wonderful things about you, if asked to be your reference.",
      "If you went into the museums industry, you would author world-renowned plaques.",
      "You've already made it this far. You are more than ready for tomorrow.",
      "You know more quotes from New Girl than the average person.",
      "It was all your design. Beause you're a mastermind.",
      "You have five children, and they all love you.",
      "Every now and then, you tweet pure brilliance.",
      "They don't call you a #sign for no reason.",
      "You give wonderful gifts.",
      "Call your boyfriend and demand he tell you something nice.",
      "You have been crowned the winner of several pub quizzes.",
      "Birds, wading in the shallow water along the shore, adore you from afar.",
      "#encouragement #encouragement"
    ]),
    superlativePerson: () => pickRandom([
      "funniest person", "kindest person", "most entertaining person", "best gossip",
      "smartest person", "fiercest person", "bravest person", "most genuine person",
      "friendliest person", "most reliable friend", "best candidate for marriage",
      "most organised person", "best travel partner", "sexiest person", "hottest person",
      "#superlativePerson AND #superlativePerson", "mother of ten"
    ]),
    trySomethingNew: () => pickRandom([
      "Try a new spot in the library.",
      "Upload an Instagram review of a hot chocolate you've never tried before.",
      "Study a new species of bird from your local environment.",
      "Read a poem you've never heard of before.",
      "Stay far away from Denmark.",
      "Find a new recipe, and someone to cook it with.",
      "Order something from Amazon.",
      "Forget about LinkedIn. Go outside. Touch grass.",
      "Watch a terrible movie.",
      "Convince a close friend to run away with you.",
      "#trySomethingNew Or maybe just: #calm."
    ]),
    calm: () => pickRandom([
      "You should let yourself have something nice. Consider trying banana bread with blueberries",
      "Don't worry about the world at large. Stay in your pyjamas all day",
      "Wear the clothes that make you feel the most at ease",
      "Listen to your favourite playlist",
      "Solve a Sudoku",
      "Listen to an episode of Off Menu",
      "Look up YouTube Bob Mortimer best clips 2024 must watch so funny",
      "Call someone you love",
      "Reap the farmland",
      "Let someone make you laugh",
    ]),
    finalSentence: () => pickRandom([
      "","","","","","","","",
      " Plus...#finalSentence",
      " Anyway...#finalSentence",
      " Oh, and I almost forgot! #flavour",
      " Wait, don't go yet. #flavour",
      " Leave someone on read.",
      " Have you forgotten the feeling of falling in love?",
      " #trySomethingNew",
      " #calm.",
      " Who's the #superlativePerson you know?",
      " You made it to September. You can finally breathe.",
      " You're feeling so far from the cliffs.",
      " The universe is shifting. It's all for you.",
      " You are no bird; and no net ensnares you; you are a free human being with an independent will.",
      " Are you more Alice or are you more Eileen?",
      " When's the last time you reread your favourite book?",
      " When's the last time you wrote someone a letter?",
      " Did you have eggs this morning?",
      " You have more charisma than the rest of this sad city combined.",
      " Google yourself.",
      " They remember the time you didn't say 'bless you'.",
      " Sneeze six times in a row.",
      " Are you married yet?",
      " #flavour",
      "#finalSentence#finalSentence",
      " Who won the Rugby last night?",
      " You're a #sign, for God's sake!",
      " I mean, you *are* a #sign, after all.",
      " It's a good thing you gave up canoeing.",
      " Saltburn bathtub scene.",
      " You really do excel at scissor pasta.",
      " Clothes are piling up on your floor.",
      " Do you need help picking out a pair of earrings?",
      " Remember: cashmere doesn't go in the washing machine.",
      " A planet is a body.",
      " Murmuration.",
      " Taylor Swift is definitely gay."
    ])
  }

  function processString(str) {
    let match, i = 0
    while(match = /\#((\w|\d)+)/g.exec(str)) {
      i++
      if(i >= 100) break
      let replacement
      if(rules[match[1]]) {
        replacement = rules[match[1]]()
      } else {
        replacement = match[1]
      }
      str = str.substring(0, match.index) + replacement + str.substring(match.index + match[0].length)
    }
    return str
  }

  return { processString }
}